package com.git.cloud.openstack.model;

public enum OpenstackManageEnum {
	
	OPENSTACK_MANAGE_USER("OPENSTACK_MANAGE_USER"),
	OPENSTACK_MANAGE_PWD("OPENSTACK_MANAGE_PWD"),
	OPENSTACK_MANAGE_PROJECT("OPENSTACK_MANAGE_PROJECT"),
	OPENSTACK_MANAGE_DOMAIN("OPENSTACK_MANAGE_DOMAIN"),
	OPENSTACK_MANAGE_ROLE("OPENSTACK_MANAGE_ROLE"),
	
	OPENSTACK_PV_MANAGE_USER("OPENSTACK_PV_MANAGE_USER"),
	OPENSTACK_PV_MANAGE_PWD("OPENSTACK_PV_MANAGE_PWD"),
	OPENSTACK_PV_MANAGE_PROJECT("OPENSTACK_PV_MANAGE_PROJECT"),
	OPENSTACK_PV_MANAGE_DOMAIN("OPENSTACK_PV_MANAGE_DOMAIN"),
	
	OPENSTACK_MANAGE_USER_SC ("OPENSTACK_MANAGE_USER_SC"),
	OPENSTACK_MANAGE_PWD_SC ("OPENSTACK_MANAGE_PWD_SC"),
	OPENSTACK_MANAGE_PROJECT_ID_SC ("OPENSTACK_MANAGE_PROJECT_ID_SC"),
	OPENSTACK_MANAGE_DOMAIN_NAME_SC ("OPENSTACK_MANAGE_DOMAIN_NAME_SC"),
	OPENSTACK_MANAGE_DOMAIN_SC ("OPENSTACK_MANAGE_DOMAIN_SC"),
	OPENSTACK_MANAGE_PROJECT_ID ("OPENSTACK_MANAGE_PROJECT_ID"),
	//6.3 SC运营管理员(创建规格使用)
	OPENSTACK_MANAGE_SYS_USER_SC ("OPENSTACK_MANAGE_SYS_USER_SC"),
	OPENSTACK_MANAGE_SYS_PWD_SC ("OPENSTACK_MANAGE_SYS_PWD_SC"),
	OPENSTACK_MANAGE_SYS_PROJECT_NAME_SC ("OPENSTACK_MANAGE_SYS_PROJECT_NAME_SC"),
	OPENSTACK_MANAGE_SYS_DOMAIN_SC ("OPENSTACK_MANAGE_SYS_DOMAIN_SC"),
	
	OPENSTACK_PHY_NET ("OPENSTACK_PHY_NET");
	
	private final String value;

	public String getValue() {
		return value;
	}
	private OpenstackManageEnum(String value) {
		this.value = value;
	}
	
	public static OpenstackManageEnum fromString(String value ) {
		if (value != null) {
			for (OpenstackManageEnum openstackManageEnum : OpenstackManageEnum.values()) {
				if (value.equalsIgnoreCase(openstackManageEnum.value)) {
					return openstackManageEnum;
				}
			}
		}
		return null;
	}
}
