// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package com.git.cloud.cloudservice.model.vo;

import com.git.cloud.common.model.base.BaseBO;

/**
 * 
 */
public class PackageModelVO extends BaseBO implements java.io.Serializable {
	/**
	 * The serial version UID of this class. Needed for serialization.
	 */
	private static final long serialVersionUID = -2064514448276203318L;

	public PackageModelVO() {
	}

	private String isActive;

	public String getIsActive() {
		return isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	private java.lang.String name;

	/**
     * 
     */
	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	private java.lang.String remark;

	/**
     * 
     */
	public java.lang.String getRemark() {
		return this.remark;
	}

	public void setRemark(java.lang.String remark) {
		this.remark = remark;
	}

	private java.lang.String filePath;

	/**
     * 
     */
	public java.lang.String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(java.lang.String filePath) {
		this.filePath = filePath;
	}

	private java.lang.String fzr;

	/**
     * 
     */
	public java.lang.String getFzr() {
		return this.fzr;
	}

	public void setFzr(java.lang.String fzr) {
		this.fzr = fzr;
	}

	private java.lang.String id;

	/**
     * 
     */
	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	private java.util.Collection modelModelVOs;

	/**
	 * Get the modelModelVOs
	 * 
	 */
	public java.util.Collection getModelModelVOs() {
		return this.modelModelVOs;
	}

	/**
	 * Sets the modelModelVOs
	 */
	public void setModelModelVOs(java.util.Collection modelModelVOs) {
		this.modelModelVOs = modelModelVOs;
	}

	/**
	 * Constructs new instances of
	 * {@link com.git.cloud.cloudservice.model.vo.PackageModelVO}.
	 */
	public static final class Factory {
		/**
		 * Constructs a new instance of
		 * {@link com.git.cloud.cloudservice.model.vo.PackageModelVO}.
		 */
		public static com.git.cloud.cloudservice.model.vo.PackageModelVO newInstance() {
			return new PackageModelVO();
		}
	}

	@Override
	public String getBizId() {
		// TODO Auto-generated method stub
		return null;
	}

}